plugins:
  - '@trivago/prettier-plugin-sort-imports'

printWidth: 119
tabWidth: 2
semi: true
singleQuote: true
trailingComma: 'all'
endOfLine: 'lf'

importOrder:
  - '^[@]*[a-z0-9](.*)$'
  - '^@/(.*)$'
  - '^[.]+/(.*)$'
importOrderSeparation: true
importOrderSortSpecifiers: true
